logging:
  level:
    root: INFO
    com:
      pinext:
        backend:
          pinextensionbackend: TRACE

server:
  port: 8085
  servlet:
    context-path: /downloader

spring:
  application:
    name: extDownloader
    profiles:
      active: dev
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties:
      hibernate:
        naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
        ddl-auto: create
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
  security:
    enabled: false

payment-wall:
  secret-key: aea088af75de6feb1da7358f976ec26c
  project-key: 91ece235b9995f8f38eb8c2d1cb0b9a5

application:
  swagger:
    enabled: true
    title: Backend app of chome extensions
    description: API
    version: 1.0.1

management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      base-path: "/"
      exposure:
        include: "*"
  metrics:
    export:
      atlas:
        enabled: false
      prometheus:
        enabled: true